apiVersion: v1
kind: Service
metadata:
  name: tfbuddy-server
  namespace: tfbuddy
  labels:
    app.kubernetes.io/name: tfbuddy-server
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: tfbuddy-server
