apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: tfbuddy-server
  namespace: tfbuddy
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tfbuddy-server
