apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  selector:
    matchLabels:
      app: ngrok
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: ngrok/ngrok
          imagePullPolicy: IfNotPresent
          args: ["http", "tfbuddy:8080"]
          ports:
            - containerPort: 4040
          envFrom:
            - secretRef:
                name: ngrok-config
          readinessProbe:
            httpGet:
              port: 4040
              path: /api/tunnels

