apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tfbuddy.fullname" . }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
    {{- include "tfbuddy.selectorLabels" . | nindent 6 }}
