{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "tfbuddy.secretsName" . }}"
  labels:
    {{- include "tfbuddy.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $index, $element := .Values.secrets.env }}
  {{ $index | quote }}: {{ $element | b64enc | quote }}
{{- end }}
{{- end }}