{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfbuddy.serviceAccountName" . }}
  labels:
    {{ include "tfbuddy.labels" . | nindent 4 }}
{{- end -}}