{{- if .Values.serviceMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tfbuddy.fullname" . }}
  labels:
    {{- include "tfbuddy.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      targetPort: {{ .Values.containerPort }}
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      {{- include "tfbuddy.selectorLabels" . | nindent 6 }}
{{- end }}